"""Create initial tables

Revision ID: 0aaa59c42c9e
Revises: e08811ecb3cb
Create Date: 2024-12-07 20:53:18.285638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaa59c42c9e'
down_revision = 'e08811ecb3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('battery_type', sa.String(length=255), nullable=True),
    sa.Column('cycle_number', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inverters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power_rating', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inverter_model', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('System_voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charging_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Voc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Vmp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Isc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Imp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('dimension', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panels')
    op.drop_table('inverters')
    op.drop_table('batteries')
    op.drop_table('products')
    # ### end Alembic commands ###
