"""add new inverter type

Revision ID: 73f520b1f552
Revises: 
Create Date: 2024-12-22 11:36:16.085587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f520b1f552'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accomplished_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('our_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('voltage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('battery_type', sa.String(length=255), nullable=False),
    sa.Column('cycle_number', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rated_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rated_voltage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poles', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inverters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inverter_type', sa.String(length=255), nullable=False),
    sa.Column('power_rating', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('system_voltage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_pv_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_pv_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mppt_voltage_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mppt_voltage_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ac_max_charging_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pv_max_charging_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_charging_current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_pv_power', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('width', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Voc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Vmp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Isc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Imp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_lamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solar_panel_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operation_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lamp_power', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wire_gauge', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wires')
    op.drop_table('solar_lamps')
    op.drop_table('panels')
    op.drop_table('inverters')
    op.drop_table('breakers')
    op.drop_table('batteries')
    op.drop_table('products')
    op.drop_table('product_types')
    op.drop_table('our_services')
    op.drop_table('admin')
    op.drop_table('accomplished_projects')
    # ### end Alembic commands ###
