"""Create initial tables

Revision ID: a44b67d30e19
Revises: 0aaa59c42c9e
Create Date: 2024-12-07 21:34:33.216258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44b67d30e19'
down_revision = '0aaa59c42c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_voltage', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('inverter_model',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('System_voltage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('System_voltage', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.alter_column('inverter_model',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('system_voltage')

    # ### end Alembic commands ###
