"""Updated backref names

Revision ID: b699094c6dcd
Revises: ce57cb773b64
Create Date: 2024-12-15 09:50:33.099276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b699094c6dcd'
down_revision = 'ce57cb773b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alpha', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('apha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apha', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.drop_column('alpha')

    # ### end Alembic commands ###
