"""Create Admin table

Revision ID: c41c1bbb5646
Revises: 
Create Date: 2024-11-27 19:48:09.364710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41c1bbb5646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('battery_type', sa.String(length=255), nullable=True),
    sa.Column('cycle_number', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inverters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power_rating', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('battery_count', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_voltage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charging_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Voc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Vmp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Isc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Imp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('dimension', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panels')
    op.drop_table('inverters')
    op.drop_table('batteries')
    op.drop_table('products')
    op.drop_table('product_types')
    op.drop_table('admin')
    # ### end Alembic commands ###
