"""Updated backref names

Revision ID: ce57cb773b64
Revises: dcda9e6c63a4
Create Date: 2024-12-15 09:25:24.494531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce57cb773b64'
down_revision = 'dcda9e6c63a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thickness', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('apha', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('efficiency')
        batch_op.drop_column('dimension')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('efficiency', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.drop_column('apha')
        batch_op.drop_column('thickness')

    # ### end Alembic commands ###
