"""Updated backref names

Revision ID: dcda9e6c63a4
Revises: a44b67d30e19
Create Date: 2024-12-12 12:33:25.607663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcda9e6c63a4'
down_revision = 'a44b67d30e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ac_max_charging_current', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pv_max_charging_current', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_charging_current', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('charging_current')
        batch_op.drop_column('inverter_model')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('model')

    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inverter_model', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('charging_current', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('max_charging_current')
        batch_op.drop_column('pv_max_charging_current')
        batch_op.drop_column('ac_max_charging_current')

    # ### end Alembic commands ###
