"""empty message

Revision ID: e08811ecb3cb
Revises: c41c1bbb5646
Create Date: 2024-11-30 15:26:58.955017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08811ecb3cb'
down_revision = 'c41c1bbb5646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inverters')
    op.drop_table('batteries')
    op.drop_table('products')
    op.drop_table('panels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('wattage', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('efficiency', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('width', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('length', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('Voc', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('Vmp', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('Isc', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('Imp', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dimension', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('brand', sa.TEXT(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('product_type_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('capacity', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('voltage', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('battery_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cycle_number', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inverters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('power_rating', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('battery_count', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_voltage', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_voltage', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_current', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('min_pv_current', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_min', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('mppt_voltage_max', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('charging_current', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_pv_power', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
